version: "2"
linters:
  default: all
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # not needed
    - exhaustruct
    - funlen            # rely on code review to limit function length
    - gochecknoglobals  # sometimes useful to declare constants
    - gocognit          # dubious "cognitive overhead" quantification
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # some unnamed constants are okay
    - nlreturn          # generous whitespace violates house style
    - noinlineerr       # excess scope violates house style
    - rowserrcheck      # no SQL code in plugins
    - sqlclosecheck     # no SQL code in plugins
    - testpackage       # internal tests are fine
    - varnamelen
    - wastedassign      # not supported with generics
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
    - wsl_v5            # generous whitespace violates house style
  settings:
    errcheck:
      check-type-assertions: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      keywords:
        - FIXME
    perfsprint:
      # Prefer sprintf for readability
      string-format: false
    tagliatelle:
      # Check the struct tag name case.
      case:
        rules:
          json: snake
          yaml: snake
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors
      # dupword reports several errors in .proto test fixtures
      # gosec reports a few minor issues in tests
      - linters:
          - dupword
          - gosec
        path: _test\.go
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bufbuild/plugins)
  exclusions:
    generated: lax
