run:
  # do not skip golangci-lint's default skip directory set
  skip-dirs-use-default: false
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate
  # default is colored-line-number
  format: colored-line-number
linters-settings:
  errcheck:
    # check for m := a.(Foo) without ok check
    check-type-assertions: true
  forbidigo:
    # Forbid the following identifiers (identifiers are written using regexp):
    forbid:
      # Ban debug statements
      - '^fmt\.Print'
      - '^print$'
      - '^println$'
      # Ban timestamppb.New because it doesn't validate. Use prototime.NewTimestamp instead.
      - '^timestamppb.New$'
      - '^os.Chdir$'
  ifshort:
    # Maximum length of variable declaration measured in number of lines, after which
    # linter won't suggest using short syntax. Has higher priority than max-decl-chars.
    max-decl-lines: 20
    # Maximum length of variable declaration measured in number of characters, after
    # which linter won't suggest using short syntax.
    max-decl-chars: 100
  lll:
    # counts tabs as tab-width
    line-length: 140
    tab-width: 4
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoinits
    - gofmt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - logrlint
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  # disable all that are not manually enabled
  disable-all: true
issues:
  exclude-rules:
    - linters:
        - stylecheck
      # this checks for no capitalization of errors
      text: "ST1005:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Password*"
      # trip this off. We should check whether we can actually remove these
      # variables altogether now.
      path: internal/bufd/bufdpersist/bufdpersist.go
      text: "G101:"
    - linters:
        - gosec
      # G203 checks for HTML being escaped, and we pass JSON verbatim in an HTML template.
      # We marshal the JSON ourselves.
      path: internal/bufd/bufdweb/handler.go
      text: "G203:"
    - linters:
        - gosec
      # G203 checks for HTML being escaped, and we pass JSON verbatim in an HTML template.
      # We marshal the JSON ourselves.
      path: internal/bufd/bufdwebstudio/handler.go
      text: "G203:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Token*"
      # trip this off.
      path: internal/pkg/github/cmd/github-releases-to-changelog/main.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Secret*"
      # trip this off.
      path: internal/bufd/bufdweb/bufdwebapp/bufdwebapp.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Secret*"
      # trip this off.
      path: internal/infra/gcpnotifierd/gcpnotifierdapp/gcpnotifierdapp.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Key*"
      # trip this off.
      path: internal/cluster/cluster_test.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Key*"
      # trip this off.
      path: internal/infra/bufgensecrets/k8sgenerator.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Secret*"
      # trip this off.
      path: internal/bufd/bufdauthn/bufdauthnapp/bufdauthnapp.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Secret*"
      # trip this off.
      path: internal/infra/linearsyncerd/linearsyncerdapp/linearsyncerdapp.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Key*"
      # trip this off.
      path: internal/bufd/bufdauthn/authorization_server_test.go
      text: "G101:"
    - linters:
        - gosec
      # G101 checks for hardcoded credentials, and the variables named "*Key*"
      # trip this off.
      path: internal/bufd/bufdgithub/processor_test.go
      text: "G101:"
    - linters:
        - gosec
      # G402 checks for uses if TLS InsecureSkipVerify, which is used in a
      # test to get the certificate of the local cluster.
      path: internal/cluster/cluster_test.go
      text: "G402:"
    - linters:
        - gosec
      # G402 checks for uses if TLS InsecureSkipVerify, which is used as
      # bufd does not have a valid certificate for in-cluster communication.
      path: internal/bufnpmd/bufnpmdapp/bufnpmdapp.go
      text: "G402:"
    - linters:
        - gosec
      # G402 checks for uses if TLS InsecureSkipVerify, which is used as
      # bufd does not have a valid certificate for in-cluster communication.
      path: internal/bufgoproxyd/bufgoproxydapp/bufgoproxydapp.go
      text: "G402:"
    - linters:
        - gosec
      # G402 checks for uses if TLS InsecureSkipVerify, which is used since we connect to Argo
      # using an IP through PSC, but the certificate is only valid for the LB domain.
      path: internal/bufmanaged/bufmanagedapp/bufmanagedapp.go
      text: "G402:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG in this test.
      path: internal/cluster/env_test.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG in this test.
      path: internal/bufd/bufdvalidate/bufdvalidate_test.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG in this test.
      path: internal/bufd/bufdociproxy/handler_test.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG here.
      path: internal/bufd/bufdplugins/pluginmanager.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG here.
      path: internal/bufd/bufdmodule/bufdmodulesync/syncer.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG in this test.
      path: internal/bufd/internal/bufdtesting/integration/env_test.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG in this test.
      path: internal/pkg/postgrestesting/postgrestesting.go
      text: "G404:"
    - linters:
        - gosec
      # G404 checks for weak RNGs. We intentionally use a predictable RNG in this test.
      path: internal/bufd/bufdauthn/auth_store_test.go
      text: "G404:"
    - linters:
        - forbidigo
      path: _test\.go
      text: "timestamppb.New"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufd/bufdapiserver/internal/repositorycommitservice
      text: "ST1003:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufpkg/genregistry/fakes_test.go
      text: "ST1003:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufpkg/genregistry/genregistrygo/fakes_test.go
      text: "ST1003:"
    - linters:
        - contextcheck
      # https://github.com/sylvia7788/contextcheck/issues/2
      path: internal/pkg/transport/http/httpserver/runner.go
      text: "Non-inherited new context"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufd/bufdhydrate/hydrator.go
      text: "ST1003:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufd/bufdhydrate/repository_commit_service.go
      text: "ST1003:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufgoproxyd/bufgoproxydmodulemanager/fakes_test.go
      text: "ST1003:"
    - linters:
        - containedctx
      # We want to embed a context here.
      path: internal/bufd/bufdpersist/bufdpersistpostgres/read_tx.go
    - linters:
        - containedctx
      # We want to detach a context here.
      path: internal/bufpkg/background/run.go
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      path: internal/bufd/bufdapiserver/internal/plugincurationservice
      text: "ST1003:"
    # Maven packages typically upload a variety of hashes (md5, sha1, sha256, sha512) for artifacts.
    # These weaker primitives are for older client versions without support for newer primitives.
    # See: https://maven.apache.org/resolver/about-checksums.html#checksum-changes
    - linters:
        - gosec
      # G401 checks for use of weak cryptographic primitive (in this case, md5 and sha1).
      path: internal/bufd/bufdmavenregistry/handler.go
      text: "G401:"
    - linters:
        - gosec
      # G501 checks for blocklisted import crypto/md5 for being a weak cryptographic primitive.
      path: internal/bufd/bufdmavenregistry/handler.go
      text: "G501:"
    - linters:
        - gosec
      # G505 checks for blocklisted import crypto/sha1 for being a weak cryptographic primitive.
      path: internal/bufd/bufdmavenregistry/handler.go
      text: "G505:"
    - linters:
        - errcheck
      # There are many http.ResponseWriter.Write commands that are not worth
      # checking the error value for.
      path: internal/infra/bufurlshortener/handler.go
    - linters:
        - staticcheck
      # Our code supports two deprecated attributes, branch & tracks
      path: internal/bufd/bufdapiserver/internal/pushservice/push.go
      text: "SA1019:"
    - linters:
        - unused
      # False positive due to lack of generics support
      path: internal/bufd/bufdauthn/scheme.go
    - linters:
        - containedctx
      # the intention here is to create a new context.Context which requires us
      # composing around the parent
      path: internal/pkg/detachcontext/detachcontext.go
    # Deprecated plugins and templates
    # To be removed after 2023-04-30 (remote generation alpha sunset)
    # See these tickets for more details:
    # - https://linear.app/bufbuild/issue/BSR-737/after-remote-generation-release-prevent-creation-of-new-templates
    # - https://linear.app/bufbuild/issue/BSR-738/after-remote-generation-release-prevent-creation-of-older-non-curated
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/displayservice/display(plugin|template)elements.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/displayservice/listmanageable(user)?(plugin|template)roles.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/internal/bufdtesting/
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/authzservice/usercan(create|delete|read)(organization)?(plugin|template)(version)?.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/authzservice/usercansee(plugin|template)settings.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/authzservice/usercanmanage(plugin|template)contributors.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdaudit/(.*).go
      text: "SA1019: auditv1alpha1(.*)(?i)(plugin)(.*)(?i)(deprecated)"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/recommendationservice/recommendedtemplates.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdociproxy/handler_test.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/searchservice/search.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdvalidate/bufdvalidate.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapidbmapping/role.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdapiserver/internal/organizationservice/updateorganizationsettings.go
      text: "SA1019:"
    - linters:
        - staticcheck
      path: internal/bufd/bufdociproxy/handler.go
      text: "SA1019:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      # This package mimics the naming of a 3rd party package.
      path: internal/pkg/argocd/argocd.go
      text: "ST1003:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      # We use IdP liberally to mean Identity Provider.
      path: internal/bufmanaged/bufmanagedtenants/internal/tenantmanager/tenantmanager.go
      text: "ST1003:"
    - linters:
        - stylecheck
      # ST1003 checks for poorly chosen identifier (ex. Id instead of ID)
      # We use IdP liberally to mean Identity Provider.
      path: internal/bufmanaged/bufmanagedtenants/bufmanagedtenantsapp/bufmanagedtenantsapp.go
      text: "ST1003:"
    - linters:
        - staticcheck
      text: "buf/alpha/registry/v1alpha1/plugin.proto is marked as deprecated"
    - linters:
        - staticcheck
      text: "buf/alpha/registry/v1alpha1/generate.proto is marked as deprecated"
    # END Deprecated plugins and templates
