run:
  # do not skip golangci-lint's default skip directory set
  skip-dirs-use-default: false
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate
  # default is colored-line-number
  format: colored-line-number
linters-settings:
  errcheck:
    # check for m := a.(Foo) without ok check
    check-type-assertions: true
  forbidigo:
    # Forbid the following identifiers (identifiers are written using regexp):
    forbid:
      # Ban debug statements
      - '^fmt\.Print'
      - '^print$'
      - '^println$'
      # Ban timestamppb.New because it doesn't validate. Use prototime.NewTimestamp instead.
      - '^timestamppb.New$'
      - '^os.Chdir$'
  ifshort:
    # Maximum length of variable declaration measured in number of lines, after which
    # linter won't suggest using short syntax. Has higher priority than max-decl-chars.
    max-decl-lines: 20
    # Maximum length of variable declaration measured in number of characters, after
    # which linter won't suggest using short syntax.
    max-decl-chars: 100
  lll:
    # counts tabs as tab-width
    line-length: 140
    tab-width: 4
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoinits
    - gofmt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - logrlint
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  # disable all that are not manually enabled
  disable-all: true
