FROM gcr.io/distroless/nodejs24-debian13:latest@sha256:ac0daf5d207757b275f3df0de9b296675500e773cc447c65afd66a948d5bf013

CMD echo this is a dummy file used to automate dependency upgrades for plugins
