FROM gcr.io/distroless/nodejs24-debian13:latest@sha256:7a22f300e7bd7ec78f3db220fb679af4e169e5f3373f97fe432847111f9b1810

CMD echo this is a dummy file used to automate dependency upgrades for plugins
