FROM gcr.io/distroless/nodejs24-debian13:latest@sha256:b1fc33242cc74151f50c62b4a03d48afd759dccf81279b5f8e401db4546479c1

CMD echo this is a dummy file used to automate dependency upgrades for plugins
