cc_binary(
    name = "protoc-gen-cpp",
    srcs = ["cpp.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-csharp",
    srcs = ["csharp.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-java",
    srcs = ["java.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-js",
    srcs = ["js.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-objectivec",
    srcs = ["objectivec.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-python",
    srcs = ["python.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-ruby",
    srcs = ["ruby.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-kotlin",
    srcs = ["kotlin.cc"],
    deps = [
        "//:protoc_lib",
    ],
)

cc_binary(
    name = "protoc-gen-php",
    srcs = ["php.cc"],
    deps = [
        "//:protoc_lib",
    ],
)
