FROM mcr.microsoft.com/dotnet/sdk:8.0.413-bookworm-slim@sha256:7fd287cec03e027e39be13fb06ca1347f1338c7a6ab4ad305d94d91852693f70

CMD echo this is a dummy file used to automate dependency upgrades for plugins
