FROM gcr.io/distroless/nodejs20-debian12:latest@sha256:3d8ce4f2928114e4c1a89c1fd327064b8a0aea40fe967793fb3f9dbea2213a39

CMD echo this is a dummy file used to automate dependency upgrades for plugins
