FROM mcr.microsoft.com/dotnet/sdk:8.0.417-bookworm-slim@sha256:1682f3cd0cb51464568de4fa88c719bd3be55539653d97540718bdd5b87062d4

CMD echo this is a dummy file used to automate dependency upgrades for plugins
