name: arm64
on:
  workflow_dispatch:
    inputs:
      plugins:
        description: "Plugins to build (i.e. connect-go:latest, connect-go, grpc/java:v1.53.0)"
        default: ''
        type: string

env:
  DOCKER_ORG: "ghcr.io/bufbuild"

# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  actions: read
  contents: read
#  packages: write

concurrency: arm64-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  arm64:
    runs-on: ubuntu-latest-4-cores
    steps:
    - name: set PLUGINS from workflow inputs
      if: ${{ inputs.plugins }}
      run: echo "PLUGINS=${{ inputs.plugins }}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
    - name: Get buf version
      shell: bash
      run: |
        echo BUF_VERSION=$(go list -m -f '{{.Version}}' github.com/bufbuild/buf | cut -c2-) >> $GITHUB_ENV
    - uses: bufbuild/buf-action@v1
      with:
        setup_only: true
    - name: Login to Docker Hub
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
#    - name: Login to GitHub Container Registry
#      if: github.repository == 'bufbuild/plugins'
#      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: make test
      env:
        DOCKER_BUILD_EXTRA_ARGS: '--platform linux/arm64'
