name: arm64
on:
  workflow_dispatch:
    inputs:
      plugins:
        description: "Plugins to build (i.e. connect-go:latest, connect-go, grpc/java:v1.53.0)"
        default: ''
        type: string

env:
  DOCKER_ORG: "ghcr.io/bufbuild"

# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  actions: read
  contents: read
#  packages: write

concurrency: arm64-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  arm64:
    runs-on: ubuntu-latest-4-cores
    steps:
    - name: set PLUGINS from workflow inputs
      if: ${{ inputs.plugins }}
      run: echo "PLUGINS=${{ inputs.plugins }}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
    - name: Get buf version
      shell: bash
      run: |
        BUF_VERSION=$(go mod edit -json | jq -r ".Require[] | select(.Path == \"github.com/bufbuild/buf\") | .Version")
        echo "BUF_VERSION=$BUF_VERSION" >> $GITHUB_ENV
    - name: Install buf cli
      run: |
        go install github.com/bufbuild/buf/cmd/buf@${BUF_VERSION}
#     uses: bufbuild/buf-setup-action@v1
#     with:
#       github_token: ${{ github.token }}
    - name: Login to Docker Hub
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4
#    - name: Login to GitHub Container Registry
#      if: github.repository == 'bufbuild/plugins'
#      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: make test
      env:
        DOCKER_BUILD_EXTRA_ARGS: '--platform linux/arm64'
