name: Deploy

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      plugin-directory:
        description: "Plugin directory"
        required: true

jobs:
  deploy-plugin:
    runs-on: ubuntu-latest
    name: Deploy plugin to BSR
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
      - name: Install buf cli
        run: |
          go install github.com/bufbuild/buf/cmd/buf@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Deploy plugin
        env:
          BUF_ALPHA_SUPPRESS_WARNINGS: 1
          BSR_USER: ${{ secrets.BSR_USER }}
          BSR_TOKEN: ${{ secrets.BSR_TOKEN }}
        shell: bash
        run: |
          echo ${BSR_TOKEN} | buf registry login --username ${BSR_USER} --token-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          PLUGIN_YAML=${{ github.event.inputs.plugin-directory }}/buf.plugin.yaml
          PLUGIN_FULL_NAME=$(yq '.name' ${PLUGIN_YAML})
          PLUGIN_OWNER=$(echo "${PLUGIN_FULL_NAME}" | cut -d '/' -f 2)
          PLUGIN_NAME=$(echo "${PLUGIN_FULL_NAME}" | cut -d '/' -f 3-)
          PLUGIN_VERSION=$(yq '.plugin_version' ${PLUGIN_YAML})
          docker pull ghcr.io/bufbuild/plugins-${PLUGIN_OWNER}-${PLUGIN_NAME}:${PLUGIN_VERSION}
          buf alpha plugin push \
            --image ghcr.io/bufbuild/plugins-${PLUGIN_OWNER}-${PLUGIN_NAME}:${PLUGIN_VERSION}
            ${{ github.event.inputs.plugin-directory }}
