name: push_all
on:
  workflow_dispatch: {} # support manual runs

# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  packages: write

concurrency: ci-${{ github.ref }}

jobs:
  push_all:
    if: github.repository == 'bufbuild/plugins'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
        check-latest: true
        cache: true
    - name: Install buf cli
      run: |
        go install github.com/bufbuild/buf/cmd/buf@main
    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      with:
        driver: docker
        driver-opts: network=host
    - name: Login to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      shell: bash
      run: make DOCKER_ORG="ghcr.io/bufbuild" DOCKER_BUILD_EXTRA_ARGS="--push"
    - name: Test
      shell: bash
      run: make test DOCKER_ORG="ghcr.io/bufbuild"
    - name: Push
      shell: bash
      env:
        BUF_ALPHA_SUPPRESS_WARNINGS: 1
        BSR_USER: ${{ secrets.BSR_USER }}
        BSR_TOKEN: ${{ secrets.BSR_TOKEN }}
      run: |
        echo ${BSR_TOKEN} | buf registry login --username ${BSR_USER} --token-stdin
        make push DOCKER_ORG="ghcr.io/bufbuild"
